### ISSUE TITLE
Flickering during a skill reflection update

### ISSUE THREAD

**Issue by vicjicaman** [Commit-Community/tessa-frontend#14]
#### Issue description
Just a little detail on the UI, whenever you select a reflection's facet option you will get a loading/disable flickering on the radio buttons.
Looks like the UI loading/disabled state is updated once per request, once for the modifications and the other for a request to get the latest state.

#### Steps to reproduce the issue
1.  Go to https://tessa.commit.community/skills/7/
2.  Career applicability
3.  Select "This skill is relevant to my career goals." then "My career goals will not require this skill."
4.  The loading/disabled state flickers sometimes

#### What's the expected result?
- The UI loading/disabled state should be kept for the complete update operation to prevent flickering.(both the update and the request of the new state).

#### What's the actual result?
- The UI loading/disable is updated twice and this creates a flickering on the controls

**Comment by vicjicaman** [comment]
Let me know if this is real issue, I can help with a pull request for this

**Comment by davidvandusen** [comment]
Hey @vicjicaman! Thanks for logging the issue.

I decided to leave the flicker in until I got around to refactoring all the API request state management to use React Query. That's done now!

The next step I intend to take on the project is to address these little annoyances, so I'm glad to know it's bugging someone else, too!

**Comment by davidvandusen** [comment]
The flicker is gone now thanks to this change: https://github.com/Commit-Community/tessa-frontend/pull/16/commits/1f6ba19dc179c06fed6df6a35a685fd44dc1425a
